# USAGE:
# conda env create -f conda-env.yaml
# conda activate datamatrix_storage

name: datamatrix_storage
channels:
  - defaults
  - pypi
dependencies:
  - python=3.8
  - pip
  - pip:
    - setuptools==58.0.4
    - -r requirements.txt
