# USAGE:
# conda env create -f conda.yaml
# conda activate datamatrix_storage

name: datamatrix_storage
channels:
  - defaults/win-32
  - pypi

variables:
  CONDA_SUBDIR: win-32

dependencies:
  - python=3.8
  - pip
  - pip:
    - setuptools==58.0.4
    - -r requirements.txt
