title = "Список разрешенных клиентов"

[clients]
[clients.scanner_1]
address = "192.168.1.20"
id = 1
name = "Scanner #1"

gateway_ip = "192.168.1.1"
netmask = ""
products = ["Ессентуки №1", "'Мятный' карась", "", "", "", ""]
server_ip = ""
server_port = 50000

[clients.scanner_2]
address = "192.168.1.10"
gateway_ip = ""
id = 2
name = "Scanner #2"
netmask = ""
products = ["", "", "", "", "", ""]
server_ip = ""
server_port = 0
