title = "Список разрешенных клиентов"

[clients]
[clients.scanner_1]
name = "Scanner #1"
address = "192.168.1.20"
id = 1

products = ["Ессентуки №1", "Мятный.карась", "", "", "", ""]
server_ip = ""
server_port = 50000
gateway_ip = "192.168.1.1"
netmask = ""


[clients.scanner_2]
name = "Scanner #2"
address = "192.168.1.10"
id = 2
products = ["", "", "", "", "", ""]
server_ip = ""
server_port = 0
gateway_ip = ""
netmask = ""
