from unittest.mock import DEFAULT
from pathlib import Path

SCANNER_SETTINGS = Path("./src/dm_storager/settings/connection_settings.json")

# SOCKET_ADDRESS = "127.0.0.1"
# SOCKET_ADDRESS = "192.168.1.58"

# SOCKET_PORT_SERVER = 5001
# SOCKET_PORT_LISTENER = 5002


DEFAULT_SCANNER_ID = 1

PREAMBULA = "RFLABC"
STATE_CONTROL_CODE = 0x37
STATE_CONTROL_RESERVED = 0x00
SETTINGS_SET_CODE = 0x13
ARCHIEVE_DATA_CODE = 0x45

SCANNER_PING_TIMEOUT = 3
